vscode:
  extensions:
    - ms-python.python
    - bungcip.better-toml
    - alexkrechik.cucumberautocomplete

tasks:
  - before: pip install poetry
    init: poetry install
    command: poetry env info
